exception TestFail of string

val run_tests : unit -> unit